version: '3.8'

services:
  app:
    build: .
    container_name: reg_users
    ports:
      - "8091:8082"
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000nN
      POSTGRES_HOST: host.docker.internal
      POSTGRES_DB: reg_user
    command: ["/bin/bash", "-c", "sleep 10 && ./build/RegUser"]

  db:
    image: postgres:latest
    container_name: db_users
    ports:
      - "8092:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000nN
      POSTGRES_HOST: host.docker.internal
      POSTGRES_DB: reg_user

    volumes:
      - pgdata:/var/lib/postgressql/data

volumes:
  pgdata:
