version: '3.8'

services:
  app:
    restart: always
    build: .
    container_name: app_file 
    ports:
      - "8081:80" 
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000nN
      POSTGRES_HOST: host.docker.internal
      
    command: ["/bin/bash", "-c", "sleep 10 && ./build/SportGym"] 

  db:
    restart: always
    image: postgres:latest
    container_name: db_all
    ports:
      - "8082:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000nN
      POSTGRES_HOST: host.docker.internal

  adding_pages:
    build: ./AddingPages/AddingPages
    container_name: adding_pages 
    ports:
      - "8083:80" 
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000nN
      POSTGRES_HOST: host.docker.internal
      
    command: ["/bin/bash", "-c", "sleep 10 && ./build/AddingPages"] 




    volumes:
      - pgdata:/var/lib/postgressql/data

volumes:
  pgdata:


