version: '3.8'

services:
  app:
    build: .
    container_name: aut_users
    ports:
      - "8085:8086"
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000nN
      POSTGRES_HOST: host.docker.internal
      POSTGRES_DB: reg_user
    command: ["/bin/bash", "-c", "sleep 10 && ./build/AuthorizationUser"]

  db:
    image: postgres:latest
    container_name: db_users_aut
    ports:
      - "8086:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000nN
      POSTGRES_HOST: host.docker.internal
      POSTGRES_DB: reg_user

    volumes:
      - pgdata:/var/lib/postgressql/data

volumes:
  pgdata:
