version: '3.8'

services:
  app:
    build: .
    container_name: gym_app
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000nN
      POSTGRES_HOST: host.docker.internal
      POSTGRES_DB: Gym
    command: ["/bin/bash", "-c", "sleep 10 && ./build/CheckGym"]

  db:
    image: postgres:latest
    container_name: gym_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000nN
      POSTGRES_HOST: host.docker.internal
      POSTGRES_DB: Gym

    volumes:
      - pgdata:/var/lib/postgressql/data

volumes:
  pgdata:
