version: '3.8'

services:
  app:
    build: .
    container_name: adding_gyms 
    ports:
      - "8081:8084" 
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000nN
      POSTGRES_HOST: host.docker.internal
      
    command: ["/bin/bash", "-c", "sleep 10 && ./build/AddingPages"] 

  db:
    image: postgres:latest
    container_name: db_adding_pages  
    ports:
      - "8082:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000nN
      POSTGRES_HOST: host.docker.internal
      POSTGRES_DB: reg_admin 

    volumes:
      - pgdata:/var/lib/postgressql/data

volumes:
  pgdata:
